spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ar7digram
    username: venzee
    password: 2472004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql